// The most important test in this lane: does the from-scratch static
// Model2Vec inference in src/embedding/ actually agree with the real
// model, not just with itself?
//
// test/integration/embedding/fixtures/potion-code-16m-v2.reference.json
// was generated by installing the upstream Python `model2vec` package
// (`pip install model2vec==0.9.0`) and calling
// `StaticModel.from_pretrained("minishlab/potion-code-16M-v2").encode([text],
// max_length=512)` for each fixture case (see the fixture's own "note"
// field). Python is used here for verification only — it is not a
// git-why product runtime dependency; nothing under src/ depends on it.
//
// This test downloads the real model into an isolated temp cache (network
// required) and asserts our TypeScript implementation's output agrees with
// the Python reference to within float16-rounding tolerance. A mismatch
// beyond that tolerance means the tokenizer, pooling, or normalization has
// a real bug, and any index built with it would look fine while retrieving
// nothing useful — this is the failure mode spec section 10 warns about.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ensureCached, type PinnedArtifact } from '../../../src/embedding/cache.js';
import { POTION_CODE_16M_V2 } from '../../../src/embedding/candidates.js';
import { parseStaticModelConfig, StaticEmbedder } from '../../../src/embedding/static-embedder.js';

interface ReferenceCase {
  readonly text: string;
  readonly num_tokens_capped: number;
  readonly token_ids_capped: readonly number[];
  readonly vector: readonly number[];
  readonly vector_norm: number;
}

interface ReferenceFile {
  readonly modelId: string;
  readonly revision: string;
  readonly dim: number;
  readonly cases: readonly ReferenceCase[];
}

const fixturePath = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  'fixtures',
  'potion-code-16m-v2.reference.json',
);
const reference = JSON.parse(readFileSync(fixturePath, 'utf8')) as ReferenceFile;

// float16 weights round-tripped through numpy vs. our float32 accumulation
// disagree by a few times 1e-4 in the worst observed dimension; 1e-2 gives
// generous headroom while still catching a real pipeline bug (which
// produces differences of order 1, not 1e-4).
const TOLERANCE = 1e-2;

async function tryDownload(artifact: PinnedArtifact, cacheDir: string) {
  try {
    return await ensureCached(artifact, { cacheDir });
  } catch (err) {
    return err instanceof Error ? err : new Error(String(err));
  }
}

test('static inference agrees with the real model2vec reference vectors', async (t) => {
  assert.equal(reference.modelId, POTION_CODE_16M_V2.modelId);
  assert.equal(reference.revision, POTION_CODE_16M_V2.revision);

  const cacheDir = fs.mkdtempSync(path.join(os.tmpdir(), 'git-why-embedding-refcheck-'));
  const result = await tryDownload(POTION_CODE_16M_V2, cacheDir);
  if (result instanceof Error) {
    t.skip(`no network access to download the reference model: ${result.message}`);
    return;
  }
  const paths = result;

  const embedder = new StaticEmbedder({
    modelId: POTION_CODE_16M_V2.modelId,
    revision: POTION_CODE_16M_V2.revision,
    config: parseStaticModelConfig(JSON.parse(readFileSync(paths.configPath, 'utf8'))),
    tokenizerJson: JSON.parse(readFileSync(paths.tokenizerPath, 'utf8')),
    weightsBuffer: readFileSync(paths.weightsPath),
    tokenizerSha256: POTION_CODE_16M_V2.tokenizer.sha256,
    weightsSha256: POTION_CODE_16M_V2.weights.sha256,
  });

  assert.equal(embedder.dimension, reference.dim);

  for (const c of reference.cases) {
    const vec = await embedder.embedQuery(c.text);
    assert.equal(vec.length, reference.dim, `dimension mismatch for ${JSON.stringify(c.text.slice(0, 30))}`);
    let maxDiff = 0;
    for (let i = 0; i < reference.dim; i++) {
      maxDiff = Math.max(maxDiff, Math.abs(vec[i]! - c.vector[i]!));
    }
    assert.ok(
      maxDiff < TOLERANCE,
      `vector for ${JSON.stringify(c.text.slice(0, 40))} diverges from the Python reference by ${maxDiff} (tolerance ${TOLERANCE})`,
    );
  }
});

test('token counts on fixed inputs match the real tokenizer, including the 512-token truncation cap', async (t) => {
  const cacheDir = fs.mkdtempSync(path.join(os.tmpdir(), 'git-why-embedding-refcheck-'));
  const result = await tryDownload(POTION_CODE_16M_V2, cacheDir);
  if (result instanceof Error) {
    t.skip(`no network access to download the reference model: ${result.message}`);
    return;
  }
  const paths = result;
  const embedder = new StaticEmbedder({
    modelId: POTION_CODE_16M_V2.modelId,
    revision: POTION_CODE_16M_V2.revision,
    config: parseStaticModelConfig(JSON.parse(readFileSync(paths.configPath, 'utf8'))),
    tokenizerJson: JSON.parse(readFileSync(paths.tokenizerPath, 'utf8')),
    weightsBuffer: readFileSync(paths.weightsPath),
    tokenizerSha256: POTION_CODE_16M_V2.tokenizer.sha256,
    weightsSha256: POTION_CODE_16M_V2.weights.sha256,
  });

  for (const c of reference.cases) {
    // countTokens() reports raw tokenization (UNK included, no 512 cap) —
    // for these fixture cases none hit UNK, so it should equal the
    // reference's post-cap count for all but the intentionally-long case.
    if (c.text.length > 0 && c.num_tokens_capped < 512) {
      assert.equal(embedder.countTokens(c.text), c.num_tokens_capped);
    }
  }

  // The long-input fixture case is deliberately over the 512-token cap;
  // confirm the boundary is exactly where model2vec's own default sits.
  const longCase = reference.cases.find((c) => c.num_tokens_capped === 512);
  assert.ok(longCase, 'fixture should include a case that hits the 512-token cap');
  assert.ok(embedder.countTokens(longCase!.text) >= 512);
});
